### ISSUE TITLE
deprecated CSSselect@0.4.1: the module is now available as 'css-select'

### ISSUE THREAD

**Issue by hthetiot** [jmc-88/grunt-appcache#11]
> npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'

via cheerio@0.18.0
```
npm ls CSSselect
└─┬ grunt-appcache@0.2.0
  └─┬ cheerio@0.18.0
    └── CSSselect@0.4.1 
```

Fixed on cheerio side:
https://github.com/cheeriojs/cheerio/blob/master/package.json#L28

**Comment by jmc-88** [comment]
This was fixed back in 04901d7fc04c0d8a6a94aab9f2f2e63d6469df21, but I forgot to reference this issue.
